# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Google/SignIn'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'mobile-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for mobile-tvOS

#   target 'mobile-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
