# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Auth', '~>5.3.0'
pod 'Firebase/Storage', '~> 5.3.0'
pod 'Firebase/Messaging', '~> 5.3.0'

target 'Raha' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Raha
  # React Native requirements
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # CodePush plugin dependency
  # Don't install via CocoaPods, getting linker issues until I installed it manually. Thread here:
  # https://github.com/Microsoft/react-native-code-push/issues/1378
  # pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # React Native App Center
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  target 'RahaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

