# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Auth', '~>5.3.0'
pod 'Firebase/Storage', '~> 5.3.0'
pod 'Firebase/Messaging', '~> 5.3.0'

target 'Raha' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Raha
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'RahaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

