/**
 * Machine-generated, unique identifier for users. Currently generated by
 * Firestore auth.
 */
export type MemberId = string;

/**
 * Unique, human-understandable identifier, currently derived from the member's
 * name
 */
export type MemberUsername = string;

/**
 * Machine-generated, unique identifier for operations.
 */
export type OperationId = string;
